import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRightLeft, Check } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { branches, motorcycles, transfers, type BranchSummary, type CreateTransferInput, type MotorcycleSearchResult } from '../api';
type Lang = 'en' | 'ar';
export default function TransferCreate({ lang }: { lang: Lang }) {
  const isRtl = lang === 'ar'; const navigate = useNavigate(); const qc = useQueryClient(); const user = JSON.parse(localStorage.getItem('pos_user') || '{}') as { branchId?: string | null };
  const branchQuery = useQuery<{ items: BranchSummary[]; total: number }>({ queryKey: ['transfer-branches'], queryFn: () => branches.list(true) }); const [fromBranchId, setFromBranchId] = useState(user.branchId ?? ''); const [toBranchId, setToBranchId] = useState(''); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [search, setSearch] = useState(''); const [notes, setNotes] = useState(''); const [error, setError] = useState('');
  const motorcycleQuery = useQuery({ queryKey: ['transfer-motorcycles', fromBranchId, search], queryFn: () => motorcycles.search({ branchId: fromBranchId, status: 'available', search: search || undefined, limit: 100 }), enabled: !!fromBranchId });
  const create = useMutation({ mutationFn: (input: CreateTransferInput) => transfers.create(input), onSuccess: () => { qc.invalidateQueries({ queryKey: ['desktop-transfers'] }); qc.invalidateQueries({ queryKey: ['desktop-inventory'] }); navigate('/transfers'); }, onError: (reason: Error) => setError(reason.message) });
  const available = (motorcycleQuery.data?.items ?? []).filter(item => item.status === 'available' && item.branch.id === fromBranchId); const branchName = (branch: { nameAr: string; nameEn: string }) => isRtl ? branch.nameAr : branch.nameEn; const toggle = (id: string) => setSelectedIds(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
  function submit(event: React.FormEvent) { event.preventDefault(); setError(''); if (!fromBranchId || !toBranchId) return setError(isRtl ? 'اختر فرعي المصدر والوجهة.' : 'Select source and destination branches.'); if (fromBranchId === toBranchId) return setError(isRtl ? 'يجب أن يختلف فرع الوجهة.' : 'Destination must differ from source.'); if (!selectedIds.length) return setError(isRtl ? 'اختر دراجة واحدة على الأقل.' : 'Select at least one motorcycle.'); create.mutate({ fromBranchId, toBranchId, motorcycleIds: selectedIds, notes: notes.trim() || undefined }); }
  return <section className="desktop-page" dir={isRtl ? 'rtl' : 'ltr'}><div className="page-heading"><div><button className="back-link" onClick={() => navigate('/transfers')}><ArrowLeft size={16} /> {isRtl ? 'التحويلات' : 'Transfers'}</button><h1>{isRtl ? 'إنشاء تحويل' : 'Create transfer'}</h1><p>{isRtl ? 'اختر الدراجات المتاحة من فرع المصدر.' : 'Select available motorcycles from the source branch.'}</p></div><ArrowRightLeft size={30} /></div><form onSubmit={submit} className="transfer-form">{error && <div className="form-error">{error}</div>}<div className="surface-panel form-grid"><label><span>{isRtl ? 'فرع المصدر' : 'Source branch'}</span><select value={fromBranchId} onChange={event => { setFromBranchId(event.target.value); setSelectedIds([]); }}><option value="">{isRtl ? 'اختر المصدر' : 'Select source'}</option>{(branchQuery.data?.items ?? []).map(branch => <option key={branch.id} value={branch.id}>{branchName(branch)}</option>)}</select></label><label><span>{isRtl ? 'فرع الوجهة' : 'Destination branch'}</span><select value={toBranchId} onChange={event => setToBranchId(event.target.value)}><option value="">{isRtl ? 'اختر الوجهة' : 'Select destination'}</option>{(branchQuery.data?.items ?? []).filter(branch => branch.id !== fromBranchId).map(branch => <option key={branch.id} value={branch.id}>{branchName(branch)}</option>)}</select></label></div><div className="surface-panel"><div className="panel-heading"><h2>{isRtl ? 'الدراجات المتاحة' : 'Available motorcycles'}</h2><span className="result-count">{selectedIds.length} {isRtl ? 'محدد' : 'selected'}</span></div><div className="search-box transfer-search"><input value={search} onChange={event => setSearch(event.target.value)} placeholder={isRtl ? 'ابحث بالموديل أو رقم الهيكل...' : 'Search model or VIN...'} /></div>{!fromBranchId ? <div className="empty-state">{isRtl ? 'اختر فرع المصدر أولاً.' : 'Select a source branch first.'}</div> : motorcycleQuery.isLoading ? <div className="state-panel">{isRtl ? 'جاري تحميل الدراجات...' : 'Loading motorcycles...'}</div> : available.length === 0 ? <div className="empty-state">{isRtl ? 'لا توجد دراجات متاحة.' : 'No available motorcycles.'}</div> : <div className="motorcycle-picker">{available.map(item => <MotorcycleOption key={item.id} item={item} selected={selectedIds.includes(item.id)} onClick={() => toggle(item.id)} lang={lang} />)}</div>}</div><div className="surface-panel"><label className="notes-field"><span>{isRtl ? 'ملاحظات' : 'Notes'}</span><textarea rows={3} value={notes} onChange={event => setNotes(event.target.value)} /></label></div><button className="primary-action" type="submit" disabled={create.isPending}>{create.isPending ? (isRtl ? 'جاري الإنشاء...' : 'Creating...') : (isRtl ? 'إنشاء التحويل' : 'Create transfer')}</button></form></section>;
}
function MotorcycleOption({ item, selected, onClick, lang }: { item: MotorcycleSearchResult; selected: boolean; onClick: () => void; lang: Lang }) { return <button type="button" className={`motorcycle-option ${selected ? 'selected' : ''}`} onClick={onClick}><span className="selection-box">{selected && <Check size={15} />}</span><span><strong>{lang === 'ar' ? item.brand.nameAr : item.brand.nameEn} {item.model}</strong><small>{item.vin} · {item.year}</small></span></button>; }