import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, RefreshCw, Search } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { transfers, type TransferStatus } from '../api';
import { DataTable, DataTableState } from '../components/DataTable';

type Lang = 'en' | 'ar';
const statuses: Array<TransferStatus | 'all'> = ['all', 'initiated', 'in_transit', 'received', 'cancelled'];
export default function Transfers({ lang }: { lang: Lang }) {
  const isRtl = lang === 'ar'; const navigate = useNavigate(); const qc = useQueryClient();
  const [status, setStatus] = useState<TransferStatus | 'all'>('all'); const [search, setSearch] = useState('');
  const list = useQuery({ queryKey: ['desktop-transfers', status, search], queryFn: () => transfers.list({ status: status === 'all' ? undefined : status, search: search || undefined }) });
  const transition = useMutation({ mutationFn: ({ id, action }: { id: string; action: 'ship' | 'receive' | 'cancel' }) => transfers[action](id), onSuccess: () => { qc.invalidateQueries({ queryKey: ['desktop-transfers'] }); qc.invalidateQueries({ queryKey: ['desktop-inventory'] }); qc.invalidateQueries({ queryKey: ['transfer-motorcycles'] }); } });
  const rows = list.data?.items ?? []; const labels: Record<string, string> = isRtl ? { all: 'الكل', initiated: 'مُنشأ', in_transit: 'قيد النقل', received: 'مستلم', cancelled: 'ملغى' } : { all: 'All', initiated: 'Initiated', in_transit: 'In transit', received: 'Received', cancelled: 'Cancelled' };
  function action(id: string, kind: 'ship' | 'receive' | 'cancel') { if (kind === 'cancel' && !window.confirm(isRtl ? 'إلغاء هذا التحويل؟' : 'Cancel this transfer?')) return; transition.mutate({ id, action: kind }); }
  return <section className="desktop-page" dir={isRtl ? 'rtl' : 'ltr'}><div className="page-heading"><div><span className="eyebrow">{isRtl ? 'حركة المخزون' : 'Inventory movement'}</span><h1>{isRtl ? 'تحويلات الفروع' : 'Branch transfers'}</h1><p>{isRtl ? 'انقل الدراجات بين الفروع وتابع حالة الشحن.' : 'Move motorcycles between branches and track each shipment.'}</p></div><div className="report-controls"><button className="secondary-action" onClick={() => list.refetch()} title={isRtl ? 'تحديث' : 'Refresh'}><RefreshCw size={16} /></button><button className="primary-action" onClick={() => navigate('/transfers/new')}><Plus size={16} /> {isRtl ? 'تحويل جديد' : 'New transfer'}</button></div></div><div className="toolbar"><div className="search-box"><Search size={17} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder={isRtl ? 'ابحث برقم التحويل...' : 'Search transfer number...'} /></div><select className="transfer-filter" value={status} onChange={event => setStatus(event.target.value as TransferStatus | 'all')}>{statuses.map(item => <option key={item} value={item}>{labels[item]}</option>)}</select><span className="result-count">{list.data?.total ?? 0} {isRtl ? 'تحويل' : 'transfers'}</span></div>{list.isLoading && <DataTableState kind="loading" lang={lang} />}{list.isError && <DataTableState kind="error" lang={lang} onRetry={() => list.refetch()} />}{!list.isLoading && !list.isError && rows.length === 0 && <DataTableState kind="empty" lang={lang} />}{!list.isLoading && !list.isError && rows.length > 0 && <DataTable className="transfer-list"><div className="transfer-header"><span>{isRtl ? 'الرقم' : 'Number'}</span><span>{isRtl ? 'من' : 'From'}</span><span>{isRtl ? 'إلى' : 'To'}</span><span>{isRtl ? 'الحالة' : 'Status'}</span><span>{isRtl ? 'الإنشاء' : 'Created'}</span><span /></div>{rows.map(row => <article className="transfer-row" key={row.id}><strong>{row.transferNumber}</strong><span>{isRtl ? row.fromBranch.nameAr : row.fromBranch.nameEn}</span><span>{isRtl ? row.toBranch.nameAr : row.toBranch.nameEn}</span><span className={`transfer-status status-${row.status}`}>{labels[row.status]}</span><time>{new Date(row.createdAt).toLocaleDateString(isRtl ? 'ar-EG' : 'en-EG')}</time><div className="transfer-actions">{row.status === 'initiated' && <><button className="secondary-action" disabled={transition.isPending} onClick={() => action(row.id, 'ship')}>{isRtl ? 'شحن' : 'Ship'}</button><button className="secondary-action danger-action" disabled={transition.isPending} onClick={() => action(row.id, 'cancel')}>{isRtl ? 'إلغاء' : 'Cancel'}</button></>}{row.status === 'in_transit' && <button className="primary-action" disabled={transition.isPending} onClick={() => action(row.id, 'receive')}>{isRtl ? 'استلام' : 'Receive'}</button>}</div></article>)}</DataTable>}</section>;
}