import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ChevronDown, ChevronRight, FolderTree, Pencil, Plus, Trash2 } from 'lucide-react';
import { categories, type CategoryCreate, type CategoryFlatItem, type CategoryResponse, type CategoryTreeItem } from '../api';
import Modal from '../components/Modal';
import Badge from '../components/Badge';

interface Props { lang: 'en' | 'ar' }
type Mode = 'create' | 'edit' | 'delete' | null;
const t = { en: { title: 'Categories', add: 'Add Category', nameAr: 'Arabic name', nameEn: 'English name', parent: 'Parent', root: 'Root category', sort: 'Sort order', status: 'Status', actions: 'Actions', save: 'Save', cancel: 'Cancel', delete: 'Delete', create: 'Create Category', edit: 'Edit Category', confirm: 'Delete this category?', loading: 'Loading…', error: 'Failed to load categories.', empty: 'No categories found.', active: 'Active', inactive: 'Inactive' }, ar: { title: 'الفئات', add: 'إضافة فئة', nameAr: 'الاسم بالعربية', nameEn: 'الاسم بالإنجليزية', parent: 'الفئة الأب', root: 'فئة رئيسية', sort: 'ترتيب العرض', status: 'الحالة', actions: 'الإجراءات', save: 'حفظ', cancel: 'إلغاء', delete: 'حذف', create: 'إنشاء فئة', edit: 'تعديل الفئة', confirm: 'حذف هذه الفئة؟', loading: 'جاري التحميل…', error: 'فشل تحميل الفئات.', empty: 'لا توجد فئات.', active: 'نشطة', inactive: 'غير نشطة' } };
const emptyForm = (): CategoryCreate & { isActive: boolean } => ({ nameAr: '', nameEn: '', parentId: '', sortOrder: 0, isActive: true });

function flatten(items: CategoryTreeItem[] | CategoryFlatItem[]): CategoryResponse[] {
  const result: CategoryResponse[] = [];
  function visit(item: CategoryTreeItem | CategoryFlatItem) { result.push(item); if ('children' in item) item.children?.forEach(visit); }
  items.forEach(visit);
  return result;
}
function Tree({ items, onEdit, onDelete, lang = 'en' }: { items: CategoryTreeItem[]; onEdit: (item: CategoryTreeItem) => void; onDelete: (item: CategoryTreeItem) => void; lang?: 'en' | 'ar' }) {
  const [open, setOpen] = useState<Record<string, boolean>>({});
  const isRtl = lang === 'ar';
  return <div>{items.map(item => <div key={item.id} style={{ marginInlineStart: item.parentId ? '1.5rem' : 0 }}><div className="flex items-center gap-2" style={{ padding: '0.7rem 0', borderBottom: '1px solid var(--border)' }}>{item.children?.length ? <button className="btn btn-outline" style={{ padding: '0.25rem' }} onClick={() => setOpen(value => ({ ...value, [item.id]: !value[item.id] }))}>{open[item.id] ? <ChevronDown size={15} /> : <ChevronRight size={15} />}</button> : <span style={{ width: 25 }} />}<FolderTree size={17} style={{ color: 'var(--accent-primary)' }} /><span style={{ flex: 1 }}>{item.nameEn} <span className="text-muted">({item.nameAr})</span></span><span className="text-muted">{item._count?.motorcycles ?? 0}</span><Badge status={item.isActive ? 'active' : 'inactive'} lang={lang} /><button className="btn btn-outline" style={{ padding: '0.3rem' }} onClick={() => onEdit(item)} title={isRtl ? 'تعديل' : 'Edit'}><Pencil size={14} /></button><button className="btn" style={{ padding: '0.3rem', background: 'var(--error-bg)', color: 'var(--error)' }} onClick={() => onDelete(item)} title={isRtl ? 'حذف' : 'Delete'}><Trash2 size={14} /></button></div>{open[item.id] && item.children && <Tree items={item.children} onEdit={onEdit} onDelete={onDelete} lang={lang} />}</div>)}</div>;
}

export default function Categories({ lang }: Props) {
  const i18n = t[lang]; const isRtl = lang === 'ar'; const qc = useQueryClient(); const [mode, setMode] = useState<Mode>(null); const [selected, setSelected] = useState<CategoryResponse | null>(null); const [form, setForm] = useState(emptyForm()); const [error, setError] = useState<string | null>(null);
  const query = useQuery({ queryKey: ['categories', 'tree'], queryFn: () => categories.list({ flat: false }) });
  const flatQuery = useQuery({ queryKey: ['categories', 'flat'], queryFn: () => categories.list({ flat: true }) });
  const createMut = useMutation({ mutationFn: (data: CategoryCreate) => categories.create(data), onSuccess: () => { qc.invalidateQueries({ queryKey: ['categories'] }); close(); }, onError: (e: Error) => setError(e.message) });
  const updateMut = useMutation({ mutationFn: ({ id, data }: { id: string; data: CategoryCreate & { isActive?: boolean } }) => categories.update(id, data), onSuccess: () => { qc.invalidateQueries({ queryKey: ['categories'] }); close(); }, onError: (e: Error) => setError(e.message) });
  const deleteMut = useMutation({ mutationFn: (id: string) => categories.delete(id), onSuccess: () => { qc.invalidateQueries({ queryKey: ['categories'] }); close(); }, onError: (e: Error) => setError(e.message) });
  function close() { setMode(null); setSelected(null); setError(null); }
  function edit(item: CategoryResponse) { setSelected(item); setForm({ nameAr: item.nameAr, nameEn: item.nameEn, parentId: item.parentId ?? '', sortOrder: item.sortOrder, isActive: item.isActive }); setError(null); setMode('edit'); }
  function submit(event: FormEvent) { event.preventDefault(); if (!form.nameAr.trim() || !form.nameEn.trim()) { setError(isRtl ? 'الاسمان مطلوبان.' : 'Both names are required.'); return; } const data = { nameAr: form.nameAr, nameEn: form.nameEn, parentId: form.parentId || undefined, sortOrder: form.sortOrder }; if (mode === 'create') createMut.mutate(data); else if (mode === 'edit' && selected) updateMut.mutate({ id: selected.id, data: { ...data, isActive: form.isActive } }); }
  const tree = (query.data ?? []) as CategoryTreeItem[]; const all = flatten((flatQuery.data ?? []) as CategoryFlatItem[]); const descendants = new Set<string>();
  function collect(id: string) { all.filter(item => item.parentId === id).forEach(child => { descendants.add(child.id); collect(child.id); }); }
  if (selected) collect(selected.id);
  const busy = createMut.isPending || updateMut.isPending || deleteMut.isPending;
  return <div className="page-container" style={{ direction: isRtl ? 'rtl' : 'ltr' }}><div className="flex items-center justify-between mb-6"><div><h1>{i18n.title}</h1><p className="text-muted">{all.length} {isRtl ? 'فئة' : 'categories'}</p></div><button className="btn btn-primary" onClick={() => { setForm(emptyForm()); setMode('create'); setError(null); }}><Plus size={16} /> {i18n.add}</button></div><div className="table-container" style={{ padding: '0 1rem' }}>{query.isLoading ? <div className="center-content"><div className="spinner" /><span>{i18n.loading}</span></div> : query.isError ? <div className="center-content" style={{ color: 'var(--error)' }}>{i18n.error}</div> : tree.length ? <Tree items={tree} onEdit={edit} onDelete={item => { setSelected(item); setError(null); setMode('delete'); }} /> : <div className="center-content"><FolderTree size={40} /><span>{i18n.empty}</span></div>}</div>{(mode === 'create' || mode === 'edit') && <Modal title={mode === 'create' ? i18n.create : i18n.edit} onClose={close} footer={<><button className="btn btn-outline" onClick={close} disabled={busy}>{i18n.cancel}</button><button className="btn btn-primary" onClick={submit as any} disabled={busy}>{i18n.save}</button></>}><form onSubmit={submit}>{error && <div className="login-error">{error}</div>}<div className="input-group"><label className="input-label">{i18n.nameAr} *</label><input className="input-field" value={form.nameAr} onChange={e => setForm(f => ({ ...f, nameAr: e.target.value }))} /></div><div className="input-group"><label className="input-label">{i18n.nameEn} *</label><input className="input-field" value={form.nameEn} onChange={e => setForm(f => ({ ...f, nameEn: e.target.value }))} /></div><div className="input-group"><label className="input-label">{i18n.parent}</label><select className="input-field" value={form.parentId ?? ''} onChange={e => setForm(f => ({ ...f, parentId: e.target.value }))}><option value="">{i18n.root}</option>{all.filter(item => item.id !== selected?.id && !descendants.has(item.id)).map(item => <option key={item.id} value={item.id}>{item.nameEn} ({item.nameAr})</option>)}</select></div><div className="input-group"><label className="input-label">{i18n.sort}</label><input className="input-field" type="number" min="0" value={form.sortOrder} onChange={e => setForm(f => ({ ...f, sortOrder: Number(e.target.value) }))} /></div></form></Modal>}{mode === 'delete' && selected && <Modal title={i18n.delete} onClose={close} footer={<><button className="btn btn-outline" onClick={close}>{i18n.cancel}</button><button className="btn" style={{ background: 'var(--error)', color: 'white' }} onClick={() => deleteMut.mutate(selected.id)} disabled={busy}>{i18n.delete}</button></>}><div>{error && <div className="login-error">{error}</div>}<p>{i18n.confirm}</p><strong>{selected.nameEn}</strong></div></Modal>}</div>;
}
